#!/bin/bash

set -euxo pipefail

DAG_HOME=${DAG_HOME:-"$HOME/repos/dag-stack"}

printf "\nUsing %s as the working directory for solving 'deploy-private-registry' challenge\n" "${DAG_HOME}"

cd "$DAG_HOME"

source "$DAG_HOME/.envrc"

TRAEFIK_LOADBALANCER_IP="$(kubectl get svc -n kube-system traefik -ojsonpath='{.status.loadBalancer.ingress[*].ip}')"
export TRAEFIK_LOADBALANCER_IP

envsubst < "$DAG_HOME/config/etc/rancher/k3s/registries.yaml" | tee /etc/rancher/k3s/registries.yaml

systemctl restart k3s

# some slack for all pods to come up
sleep 10